const router = require('express').Router();
const c = require('../controllers/membroController');
const admin = require('../middlewares/auth');
const member = require('../middlewares/authMembro');
const limit = require('../middlewares/accountLimiter');
router.param('id',(req,res,next,id) => /^[1-9]\d{0,9}$/.test(id) ? next() : res.status(400).json({success:false,message:'ID inválido.'}));
router.post('/',limit('signup',5),c.criar);
router.post('/login',limit('member-login',8),c.login);
router.get('/sessao',c.sessao);
router.post('/esqueci-senha',limit('recovery',3),c.esqueciSenha);
router.post('/redefinir-senha',limit('reset',8),c.redefinirSenha);
router.post('/confirmar-email',limit('confirm',8),c.confirmarEmail);
router.get('/redefinir-senha',(req,res) => res.redirect('/redefinir-senha?token='+encodeURIComponent(typeof req.query.token === 'string' ? req.query.token : '')));
router.get('/',admin,c.listar);
router.get('/lista',member,c.listarNomes);
router.get('/dashboard',admin,c.dashboard);
router.get('/ultimos',admin,c.ultimos);
router.get('/validar/:id',c.validar);
router.post('/presenca/:id',admin,limit('attendance',60,60),c.presenca);
router.get('/qrcode/:id',admin,c.baixarQRCode);
router.get('/perfil',member,c.perfil);
router.get('/:id',admin,c.buscarPorId);
router.put('/:id',admin,c.atualizar);
router.delete('/:id',admin,c.excluir);
module.exports = router;
